set root_dir   [file dirname [info script]]
# A versioned build directory prevents Vivado from reusing the generated IP,
# run database, HWH, or bitstream from the earlier selectable-decimator design.
set build_dir  [file join $root_dir build]

create_project -force top_design $build_dir \
    -part xczu28dr-ffvg1517-2-e

set_property board_part xilinx.com:zcu111:part0:1.2 [current_project]
set_property target_language VHDL [current_project]

# Repository-contained custom IP.
# set_property ip_repo_paths [file join $root_dir ip_repo] [current_project]
# update_ip_catalog -rebuild


# IP Integrator block-design recreation.
source [file join $root_dir top_design.tcl]

validate_bd_design
save_bd_design

# Global block-design synthesis avoids per-IP out-of-context runs.
set bd_file [get_files */top_design.bd]
set_property synth_checkpoint_mode None $bd_file

# Top-level HDL wrapper generated by Vivado.
set wrapper_files [make_wrapper -files $bd_file -top]
add_files -norecurse $wrapper_files

set_property top top_design_wrapper [current_fileset]
update_compile_order -fileset sources_1

puts "Project created at:"
puts [file join $build_dir top_design.xpr]
