"""Rates and UDP values shared by the board and host."""

import struct

ADC_SAMPLE_RATE_HZ = 2_560_000_000
RFDC_DECIMATION = 8
RFDC_FABRIC_WORDS = 2
RFDC_FABRIC_CLOCK_HZ = 160_000_000
PL_DECIMATION = 32
PL_DECIMATION_SELECT = 5
IQ_SAMPLE_RATE_HZ = ADC_SAMPLE_RATE_HZ // (RFDC_DECIMATION * PL_DECIMATION)
HARDWARE_BUILD_ID = 0xA833
EXPECTED_OUTPUT_VALID_INTERVAL = PL_DECIMATION // RFDC_FABRIC_WORDS
EXPECTED_AXIS_CLOCKS_PER_MS = RFDC_FABRIC_CLOCK_HZ // 1000

UDP_MAGIC = b"IQ10"
UDP_HEADER = struct.Struct("!4sIIIQ")
UDP_IQ_BYTES = 1024
