set script_dir [file dirname [file normalize [info script]]]
set root_dir   [file normalize [file join $script_dir ..]]
# A versioned build directory prevents Vivado from reusing the generated IP,
# run database, HWH, or bitstream from the earlier selectable-decimator design.
set build_dir  [file join $root_dir build_rfdc8_fir32_clk160_v2]

create_project -force adsb_capture $build_dir \
    -part xczu28dr-ffvg1517-2-e

set_property board_part xilinx.com:zcu111:part0:1.2 [current_project]
set_property target_language Verilog [current_project]

# Repository-contained custom IP.
set_property ip_repo_paths [file join $root_dir ip_repo] [current_project]
update_ip_catalog -rebuild

# Custom RTL is loaded before the module reference is recreated.
add_files -norecurse \
    [file join $root_dir rtl axis_capture_gate.v]

# Handwritten XDC files, when present.
foreach xdc_file [glob -nocomplain \
        -directory [file join $root_dir constraints] *.xdc] {
    add_files -fileset constrs_1 -norecurse $xdc_file
}

# IP Integrator block-design recreation.
source [file join $script_dir adsb_capture_bd.tcl]

validate_bd_design
save_bd_design

# Global block-design synthesis avoids per-IP out-of-context runs.
set bd_file [get_files */adsb_capture.bd]
set_property synth_checkpoint_mode None $bd_file

# Top-level HDL wrapper generated by Vivado.
set wrapper_files [make_wrapper -files $bd_file -top]
add_files -norecurse $wrapper_files

set_property top adsb_capture_wrapper [current_fileset]
update_compile_order -fileset sources_1

puts "Project created at:"
puts [file join $build_dir adsb_capture.xpr]
